name: Despliegue de Bot de Telegram

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Configura Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Instala librerías necesarias
      run: |
        python -m pip install --upgrade pip
        pip install telebot textblob tensorflow numpy  # Agrega aquí las librerías que tu bot utiliza

    - name: Ejecuta el bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: python Bot.py
